// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_auth.go -package=mocks -source=contract.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/ksusonic/niti/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockrefreshTokenRepo is a mock of refreshTokenRepo interface.
type MockrefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockrefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockrefreshTokenRepoMockRecorder is the mock recorder for MockrefreshTokenRepo.
type MockrefreshTokenRepoMockRecorder struct {
	mock *MockrefreshTokenRepo
}

// NewMockrefreshTokenRepo creates a new mock instance.
func NewMockrefreshTokenRepo(ctrl *gomock.Controller) *MockrefreshTokenRepo {
	mock := &MockrefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockrefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrefreshTokenRepo) EXPECT() *MockrefreshTokenRepoMockRecorder {
	return m.recorder
}

// GetValid mocks base method.
func (m *MockrefreshTokenRepo) GetValid(ctx context.Context, jti uuid.UUID) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValid", ctx, jti)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValid indicates an expected call of GetValid.
func (mr *MockrefreshTokenRepoMockRecorder) GetValid(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValid", reflect.TypeOf((*MockrefreshTokenRepo)(nil).GetValid), ctx, jti)
}

// Insert mocks base method.
func (m *MockrefreshTokenRepo) Insert(ctx context.Context, token models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockrefreshTokenRepoMockRecorder) Insert(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockrefreshTokenRepo)(nil).Insert), ctx, token)
}

// Revoke mocks base method.
func (m *MockrefreshTokenRepo) Revoke(ctx context.Context, jti uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockrefreshTokenRepoMockRecorder) Revoke(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockrefreshTokenRepo)(nil).Revoke), ctx, jti)
}
