// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_deps.go -package=mocks -source=deps.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeps is a mock of Deps interface.
type MockDeps struct {
	ctrl     *gomock.Controller
	recorder *MockDepsMockRecorder
	isgomock struct{}
}

// MockDepsMockRecorder is the mock recorder for MockDeps.
type MockDepsMockRecorder struct {
	mock *MockDeps
}

// NewMockDeps creates a new mock instance.
func NewMockDeps(ctrl *gomock.Controller) *MockDeps {
	mock := &MockDeps{ctrl: ctrl}
	mock.recorder = &MockDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeps) EXPECT() *MockDepsMockRecorder {
	return m.recorder
}

// ValidateAccessToken mocks base method.
func (m *MockDeps) ValidateAccessToken(tokenStr string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenStr)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockDepsMockRecorder) ValidateAccessToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockDeps)(nil).ValidateAccessToken), tokenStr)
}
