// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_deps.go -package=mocks -source=deps.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthDeps is a mock of AuthDeps interface.
type MockAuthDeps struct {
	ctrl     *gomock.Controller
	recorder *MockAuthDepsMockRecorder
	isgomock struct{}
}

// MockAuthDepsMockRecorder is the mock recorder for MockAuthDeps.
type MockAuthDepsMockRecorder struct {
	mock *MockAuthDeps
}

// NewMockAuthDeps creates a new mock instance.
func NewMockAuthDeps(ctrl *gomock.Controller) *MockAuthDeps {
	mock := &MockAuthDeps{ctrl: ctrl}
	mock.recorder = &MockAuthDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthDeps) EXPECT() *MockAuthDepsMockRecorder {
	return m.recorder
}

// ValidateAccessToken mocks base method.
func (m *MockAuthDeps) ValidateAccessToken(tokenStr string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenStr)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockAuthDepsMockRecorder) ValidateAccessToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockAuthDeps)(nil).ValidateAccessToken), tokenStr)
}
