// Package publicapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package publicapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// DJ defines model for DJ.
type DJ struct {
	AvatarUrl *string  `json:"avatar_url,omitempty"`
	Socials   []Social `json:"socials"`
	StageName string   `json:"stage_name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Description       string     `json:"description"`
	Djs               []DJ       `json:"djs"`
	Id                int        `json:"id"`
	IsSubscribed      bool       `json:"is_subscribed"`
	Location          *string    `json:"location,omitempty"`
	ParticipantsCount *int       `json:"participants_count,omitempty"`
	StartsAt          *time.Time `json:"starts_at,omitempty"`
	Title             string     `json:"title"`
	VideoUrl          *string    `json:"video_url,omitempty"`
}

// Social defines model for Social.
type Social struct {
	Icon *string `json:"icon,omitempty"`
	Name string  `json:"name"`
	Url  string  `json:"url"`
}

// User defines model for User.
type User struct {
	AvatarUrl  *string `json:"avatar_url,omitempty"`
	FirstName  string  `json:"first_name"`
	IsDj       bool    `json:"is_dj"`
	LastName   *string `json:"last_name,omitempty"`
	TelegramId int64   `json:"telegram_id"`
	Username   string  `json:"username"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	AvatarUrl     *string `json:"avatar_url,omitempty"`
	FirstName     string  `json:"first_name"`
	IsDj          bool    `json:"is_dj"`
	LastName      *string `json:"last_name,omitempty"`
	Subscriptions []Event `json:"subscriptions"`
	TelegramId    int64   `json:"telegram_id"`
	Username      string  `json:"username"`
}

// AuthRefreshTokenJSONBody defines parameters for AuthRefreshToken.
type AuthRefreshTokenJSONBody struct {
	// RefreshToken Refresh token
	RefreshToken string `json:"refresh_token"`
}

// AuthTelegramInitDataJSONBody defines parameters for AuthTelegramInitData.
type AuthTelegramInitDataJSONBody struct {
	// InitData Telegram initData string
	InitData *string `json:"init_data,omitempty"`
}

// EventsParams defines parameters for Events.
type EventsParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of events to skip before starting to collect the result set
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AuthRefreshTokenJSONRequestBody defines body for AuthRefreshToken for application/json ContentType.
type AuthRefreshTokenJSONRequestBody AuthRefreshTokenJSONBody

// AuthTelegramInitDataJSONRequestBody defines body for AuthTelegramInitData for application/json ContentType.
type AuthTelegramInitDataJSONRequestBody AuthTelegramInitDataJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/refresh)
	AuthRefreshToken(c *gin.Context)

	// (POST /auth/telegram-init-data)
	AuthTelegramInitData(c *gin.Context)

	// (GET /events)
	Events(c *gin.Context, params EventsParams)

	// (GET /health)
	Healthcheck(c *gin.Context)

	// (GET /profile)
	GetProfile(c *gin.Context)

	// (POST /subscribe/{id})
	SubscribeEvent(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AuthRefreshToken operation middleware
func (siw *ServerInterfaceWrapper) AuthRefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AuthRefreshToken(c)
}

// AuthTelegramInitData operation middleware
func (siw *ServerInterfaceWrapper) AuthTelegramInitData(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AuthTelegramInitData(c)
}

// Events operation middleware
func (siw *ServerInterfaceWrapper) Events(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params EventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Events(c, params)
}

// Healthcheck operation middleware
func (siw *ServerInterfaceWrapper) Healthcheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthcheck(c)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c)
}

// SubscribeEvent operation middleware
func (siw *ServerInterfaceWrapper) SubscribeEvent(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubscribeEvent(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/refresh", wrapper.AuthRefreshToken)
	router.POST(options.BaseURL+"/auth/telegram-init-data", wrapper.AuthTelegramInitData)
	router.GET(options.BaseURL+"/events", wrapper.Events)
	router.GET(options.BaseURL+"/health", wrapper.Healthcheck)
	router.GET(options.BaseURL+"/profile", wrapper.GetProfile)
	router.POST(options.BaseURL+"/subscribe/:id", wrapper.SubscribeEvent)
}

type AuthRefreshTokenRequestObject struct {
	Body *AuthRefreshTokenJSONRequestBody
}

type AuthRefreshTokenResponseObject interface {
	VisitAuthRefreshTokenResponse(w http.ResponseWriter) error
}

type AuthRefreshToken200JSONResponse struct {
	// AccessToken New short-lived JWT
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Rotated refresh token
	RefreshToken string `json:"refresh_token"`
}

func (response AuthRefreshToken200JSONResponse) VisitAuthRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthRefreshToken400JSONResponse Error

func (response AuthRefreshToken400JSONResponse) VisitAuthRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthRefreshToken500JSONResponse Error

func (response AuthRefreshToken500JSONResponse) VisitAuthRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthTelegramInitDataRequestObject struct {
	Body *AuthTelegramInitDataJSONRequestBody
}

type AuthTelegramInitDataResponseObject interface {
	VisitAuthTelegramInitDataResponse(w http.ResponseWriter) error
}

type AuthTelegramInitData200JSONResponse struct {
	// AccessToken Short JWT token
	AccessToken string `json:"access_token"`

	// ExpiresIn Token expiration time in seconds
	ExpiresIn int `json:"expires_in"`

	// RefreshToken JWT token for refreshing access token
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

func (response AuthTelegramInitData200JSONResponse) VisitAuthTelegramInitDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthTelegramInitData400JSONResponse Error

func (response AuthTelegramInitData400JSONResponse) VisitAuthTelegramInitDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthTelegramInitData401JSONResponse Error

func (response AuthTelegramInitData401JSONResponse) VisitAuthTelegramInitDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthTelegramInitData500JSONResponse Error

func (response AuthTelegramInitData500JSONResponse) VisitAuthTelegramInitDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EventsRequestObject struct {
	Params EventsParams
}

type EventsResponseObject interface {
	VisitEventsResponse(w http.ResponseWriter) error
}

type Events200JSONResponse []Event

func (response Events200JSONResponse) VisitEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Events401JSONResponse Error

func (response Events401JSONResponse) VisitEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Events500JSONResponse Error

func (response Events500JSONResponse) VisitEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HealthcheckRequestObject struct {
}

type HealthcheckResponseObject interface {
	VisitHealthcheckResponse(w http.ResponseWriter) error
}

type Healthcheck200JSONResponse struct {
	Status string `json:"status"`
}

func (response Healthcheck200JSONResponse) VisitHealthcheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileRequestObject struct {
}

type GetProfileResponseObject interface {
	VisitGetProfileResponse(w http.ResponseWriter) error
}

type GetProfile200JSONResponse UserProfile

func (response GetProfile200JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile401JSONResponse Error

func (response GetProfile401JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile404JSONResponse Error

func (response GetProfile404JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile500JSONResponse Error

func (response GetProfile500JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SubscribeEventRequestObject struct {
	Id int `json:"id"`
}

type SubscribeEventResponseObject interface {
	VisitSubscribeEventResponse(w http.ResponseWriter) error
}

type SubscribeEvent200JSONResponse struct {
	Message           *string `json:"message,omitempty"`
	ParticipantsCount *int    `json:"participants_count,omitempty"`
	Success           *bool   `json:"success,omitempty"`
}

func (response SubscribeEvent200JSONResponse) VisitSubscribeEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SubscribeEvent401JSONResponse Error

func (response SubscribeEvent401JSONResponse) VisitSubscribeEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SubscribeEvent404JSONResponse Error

func (response SubscribeEvent404JSONResponse) VisitSubscribeEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SubscribeEvent500JSONResponse Error

func (response SubscribeEvent500JSONResponse) VisitSubscribeEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/refresh)
	AuthRefreshToken(ctx context.Context, request AuthRefreshTokenRequestObject) (AuthRefreshTokenResponseObject, error)

	// (POST /auth/telegram-init-data)
	AuthTelegramInitData(ctx context.Context, request AuthTelegramInitDataRequestObject) (AuthTelegramInitDataResponseObject, error)

	// (GET /events)
	Events(ctx context.Context, request EventsRequestObject) (EventsResponseObject, error)

	// (GET /health)
	Healthcheck(ctx context.Context, request HealthcheckRequestObject) (HealthcheckResponseObject, error)

	// (GET /profile)
	GetProfile(ctx context.Context, request GetProfileRequestObject) (GetProfileResponseObject, error)

	// (POST /subscribe/{id})
	SubscribeEvent(ctx context.Context, request SubscribeEventRequestObject) (SubscribeEventResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AuthRefreshToken operation middleware
func (sh *strictHandler) AuthRefreshToken(ctx *gin.Context) {
	var request AuthRefreshTokenRequestObject

	var body AuthRefreshTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthRefreshToken(ctx, request.(AuthRefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthRefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(AuthRefreshTokenResponseObject); ok {
		if err := validResponse.VisitAuthRefreshTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthTelegramInitData operation middleware
func (sh *strictHandler) AuthTelegramInitData(ctx *gin.Context) {
	var request AuthTelegramInitDataRequestObject

	var body AuthTelegramInitDataJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthTelegramInitData(ctx, request.(AuthTelegramInitDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthTelegramInitData")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(AuthTelegramInitDataResponseObject); ok {
		if err := validResponse.VisitAuthTelegramInitDataResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Events operation middleware
func (sh *strictHandler) Events(ctx *gin.Context, params EventsParams) {
	var request EventsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Events(ctx, request.(EventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Events")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(EventsResponseObject); ok {
		if err := validResponse.VisitEventsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Healthcheck operation middleware
func (sh *strictHandler) Healthcheck(ctx *gin.Context) {
	var request HealthcheckRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Healthcheck(ctx, request.(HealthcheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthcheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthcheckResponseObject); ok {
		if err := validResponse.VisitHealthcheckResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfile operation middleware
func (sh *strictHandler) GetProfile(ctx *gin.Context) {
	var request GetProfileRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfile(ctx, request.(GetProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetProfileResponseObject); ok {
		if err := validResponse.VisitGetProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubscribeEvent operation middleware
func (sh *strictHandler) SubscribeEvent(ctx *gin.Context, id int) {
	var request SubscribeEventRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SubscribeEvent(ctx, request.(SubscribeEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubscribeEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SubscribeEventResponseObject); ok {
		if err := validResponse.VisitSubscribeEventResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
