// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_auth.go -package=mocks -source=contract.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ksusonic/niti/backend/internal/models"
	initdata "github.com/telegram-mini-apps/init-data-golang"
	gomock "go.uber.org/mock/gomock"
)

// Mockauth is a mock of auth interface.
type Mockauth struct {
	ctrl     *gomock.Controller
	recorder *MockauthMockRecorder
	isgomock struct{}
}

// MockauthMockRecorder is the mock recorder for Mockauth.
type MockauthMockRecorder struct {
	mock *Mockauth
}

// NewMockauth creates a new mock instance.
func NewMockauth(ctrl *gomock.Controller) *Mockauth {
	mock := &Mockauth{ctrl: ctrl}
	mock.recorder = &MockauthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauth) EXPECT() *MockauthMockRecorder {
	return m.recorder
}

// GenerateTokens mocks base method.
func (m *Mockauth) GenerateTokens(arg0 context.Context, arg1 int64) (models.JWTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", arg0, arg1)
	ret0, _ := ret[0].(models.JWTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockauthMockRecorder) GenerateTokens(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*Mockauth)(nil).GenerateTokens), arg0, arg1)
}

// ParseInitData mocks base method.
func (m *Mockauth) ParseInitData(arg0 string) (*initdata.InitData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInitData", arg0)
	ret0, _ := ret[0].(*initdata.InitData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseInitData indicates an expected call of ParseInitData.
func (mr *MockauthMockRecorder) ParseInitData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInitData", reflect.TypeOf((*Mockauth)(nil).ParseInitData), arg0)
}

// RollTokens mocks base method.
func (m *Mockauth) RollTokens(ctx context.Context, refresh *models.RefreshToken) (*models.JWTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollTokens", ctx, refresh)
	ret0, _ := ret[0].(*models.JWTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollTokens indicates an expected call of RollTokens.
func (mr *MockauthMockRecorder) RollTokens(ctx, refresh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollTokens", reflect.TypeOf((*Mockauth)(nil).RollTokens), ctx, refresh)
}

// ValidateRefreshToken mocks base method.
func (m *Mockauth) ValidateRefreshToken(ctx context.Context, refreshTokenStr string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", ctx, refreshTokenStr)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockauthMockRecorder) ValidateRefreshToken(ctx, refreshTokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*Mockauth)(nil).ValidateRefreshToken), ctx, refreshTokenStr)
}
