// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_auth.go -package=mocks -source=contract.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ksusonic/niti/backend/internal/models"
	initdata "github.com/telegram-mini-apps/init-data-golang"
	gomock "go.uber.org/mock/gomock"
)

// Mockauth is a mock of auth interface.
type Mockauth struct {
	ctrl     *gomock.Controller
	recorder *MockauthMockRecorder
	isgomock struct{}
}

// MockauthMockRecorder is the mock recorder for Mockauth.
type MockauthMockRecorder struct {
	mock *Mockauth
}

// NewMockauth creates a new mock instance.
func NewMockauth(ctrl *gomock.Controller) *Mockauth {
	mock := &Mockauth{ctrl: ctrl}
	mock.recorder = &MockauthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauth) EXPECT() *MockauthMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *Mockauth) GenerateToken(arg0 context.Context, arg1 int64) (models.JWTAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0, arg1)
	ret0, _ := ret[0].(models.JWTAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockauthMockRecorder) GenerateToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*Mockauth)(nil).GenerateToken), arg0, arg1)
}

// ParseInitData mocks base method.
func (m *Mockauth) ParseInitData(arg0 string) (*initdata.InitData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInitData", arg0)
	ret0, _ := ret[0].(*initdata.InitData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseInitData indicates an expected call of ParseInitData.
func (mr *MockauthMockRecorder) ParseInitData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInitData", reflect.TypeOf((*Mockauth)(nil).ParseInitData), arg0)
}
