// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_auth.go -package=mocks -source=contract.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ksusonic/niti/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// Mockauth is a mock of auth interface.
type Mockauth struct {
	ctrl     *gomock.Controller
	recorder *MockauthMockRecorder
	isgomock struct{}
}

// MockauthMockRecorder is the mock recorder for Mockauth.
type MockauthMockRecorder struct {
	mock *Mockauth
}

// NewMockauth creates a new mock instance.
func NewMockauth(ctrl *gomock.Controller) *Mockauth {
	mock := &Mockauth{ctrl: ctrl}
	mock.recorder = &MockauthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauth) EXPECT() *MockauthMockRecorder {
	return m.recorder
}

// GenerateTokens mocks base method.
func (m *Mockauth) GenerateTokens(ctx context.Context, userID int64) (models.JWTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", ctx, userID)
	ret0, _ := ret[0].(models.JWTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockauthMockRecorder) GenerateTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*Mockauth)(nil).GenerateTokens), ctx, userID)
}

// ParseInitData mocks base method.
func (m *Mockauth) ParseInitData(initData string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInitData", initData)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseInitData indicates an expected call of ParseInitData.
func (mr *MockauthMockRecorder) ParseInitData(initData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInitData", reflect.TypeOf((*Mockauth)(nil).ParseInitData), initData)
}

// RollTokens mocks base method.
func (m *Mockauth) RollTokens(ctx context.Context, refresh *models.RefreshToken) (*models.JWTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollTokens", ctx, refresh)
	ret0, _ := ret[0].(*models.JWTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollTokens indicates an expected call of RollTokens.
func (mr *MockauthMockRecorder) RollTokens(ctx, refresh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollTokens", reflect.TypeOf((*Mockauth)(nil).RollTokens), ctx, refresh)
}

// ValidateRefreshToken mocks base method.
func (m *Mockauth) ValidateRefreshToken(ctx context.Context, refreshTokenStr string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", ctx, refreshTokenStr)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockauthMockRecorder) ValidateRefreshToken(ctx, refreshTokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*Mockauth)(nil).ValidateRefreshToken), ctx, refreshTokenStr)
}

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
	isgomock struct{}
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockusersRepo) Create(ctx context.Context, in *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockusersRepoMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockusersRepo)(nil).Create), ctx, in)
}
